# Copyright (c) 2026 NyxeraLabs
# Author: José María Micoli
# Licensed under BSL 1.1
# Change Date: 2033-02-17 → Apache-2.0
#
# You may:
# ✔ Study
# ✔ Modify
# ✔ Use for internal security testing
#
# You may NOT:
# ✘ Offer as a commercial service
# ✘ Sell derived competing products

services:
  mongodb:
    image: mongo:7.0
    container_name: nyxera-mongodb
    restart: unless-stopped
    command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./config/mongodb/mongod.conf:/etc/mongod.conf:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok"]
      interval: 20s
      timeout: 10s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: nyxera-opensearch
    restart: unless-stopped
    environment:
      discovery.type: "single-node"
      plugins.security.disabled: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  redis:
    image: redis:7.2-alpine
    container_name: nyxera-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:RELEASE.2026-02-12T03-09-05Z
    container_name: nyxera-minio
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: nyxeraadmin
      MINIO_ROOT_PASSWORD: nyxera-change-me
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: nyxera-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:11.1.4
    container_name: nyxera-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: nyxeraadmin
      GF_SECURITY_ADMIN_PASSWORD: nyxera-change-me
      GF_USERS_ALLOW_SIGN_UP: "false"
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mongo_data:
  opensearch_data:
  redis_data:
  minio_data:
  prometheus_data:
  grafana_data:
